Numpy Array Operations:

In [85]:
#1. Create a 1D NumPy Array: 

import numpy as np
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print (temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]

In [86]:
# 2. Inspection and Properties:

temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print (temperatures_w1.shape)
print(temperatures_w1.size)
print(temperatures_w1.dtype)

(7,)
7
float64

In [87]:
# 3. Array Operations:
# ● Find the maximum, minimum, and mean temperatures for the week.

temperatures_w1_f = (temperatures_w1 * 9/5) + 32
print(temperatures_w1_f)

print(np.max(temperatures_w1_f))
print(np.min(temperatures_w1_f))
print(np.mean(temperatures_w1_f))

[72.5  77.54 69.44 74.12 78.98 76.64 71.42]
78.98
69.44
74.37714285714286

In [88]:
# 4. Array Slicing and Indexing:
print(temperatures_w1[0:3])
print(temperatures_w1[-2:])
print(temperatures_w1[2:5])

[22.5 25.3 20.8]
[24.8 21.9]
[20.8 23.4 26.1]

In [89]:
# 5. Create a 2D Array:

temperatures=np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],[19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])
print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]

In [90]:
# 6.  A .Inspect and Slice the 2D Array: 

print (temperatures.shape)
print(temperatures.size)
print(temperatures.dtype)

(2, 7)
14
float64

In [91]:
# B. Extract the temperatures for each week and the weekends (last two days) for both weeks.

week_1 = temperatures[0, :]
week_2 = temperatures[1, :]
weekends = temperatures[:, -2:]

print(week_1)
print(week_2)
print(weekends)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
[19.2 22.5 21.3 24.  23.5 22.8 20.1]
[[24.8 21.9]
 [22.8 20.1]]

Pandas Series:

In [92]:
import pandas as pd

In [93]:
# 1. Creating Pandas Series:

marks= pd.Series([95, 92, 89, 85, 80 ],index = ['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])
print (marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

In [94]:
# 2. Indexing and Slicing:

print(marks.iloc[0])

print(marks.loc["Rank1":"Rank3"])

print(marks.loc["Rank3"])

highrank= marks[marks > 90]

highrank

95
Rank1    95
Rank2    92
Rank3    89
dtype: int64
89

Rank1    95
Rank2    92
dtype: int64

In [95]:
# 3. Manipulating Series:
marks.loc['Rank1'] = 100
print(marks)

marks = marks.drop('Rank5')
print(marks)

cgpa = marks / 10
print(cgpa)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64

Pandas DataFrame

In [96]:
# 1. Creating Pandas DataFrame: 

data = {
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture',
                        'Clothing', 'Electronics', 'Furniture', 'Clothing',
                        'Furniture', 'Electronics'],
    'Region': ['North', 'South', 'North', 'East', 'West',
               'North', 'East', 'West', 'South', 'North'],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
}

transactions = pd.DataFrame(data)
transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

 2. Data Exploration:

In [97]:

#  Display the transactions DataFrame and its basic information, including head, tail, shape, column names, and data types. 

transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [98]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TransactionID    10 non-null     int64
 1   ProductCategory  10 non-null     str
 2   Region           10 non-null     str
 3   Amount           10 non-null     int64
dtypes: int64(2), str(2)
memory usage: 452.0 bytes

In [99]:
transactions.head()

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

In [100]:
transactions.tail()

   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [101]:
transactions.shape

(10, 4)

In [102]:
transactions.columns

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='str')

In [103]:
transactions.dtypes

TransactionID      int64
ProductCategory      str
Region               str
Amount             int64
dtype: object

In [104]:
# ● Display only the 'ProductCategory' and 'Amount' columns. 

transactions[["ProductCategory","Amount"]]

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

In [105]:
# ● Retrieve the last 3 columns of the DataFrame using iloc or loc.
transactions.iloc[:, -3:]

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

In [106]:
transactions.loc[:, 'ProductCategory':'Amount']

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

In [107]:
#  Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.

north_above_200 = transactions[(transactions['Region'] == 'North') & (transactions['Amount'] > 200)]
north_above_200

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

In [108]:
# ● Find the value counts for the 'ProductCategory' column.

transactions['ProductCategory'].value_counts

<bound method IndexOpsMixin.value_counts of 0    Electronics
1       Clothing
2    Electronics
3      Furniture
4       Clothing
5    Electronics
6      Furniture
7       Clothing
8      Furniture
9    Electronics
Name: ProductCategory, dtype: str>

In [109]:
# ● Find the unique values in the 'Region' column. 

transactions['Region'].unique()

<StringArray>
['North', 'South', 'East', 'West']
Length: 4, dtype: str

In [110]:
# ● Group by 'Region' and find the mean amount for each region.

transactions.groupby('Region')['Amount'].mean()

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

3. Manipulating the DataFrame:

In [111]:
# ● Modify the 'Amount' for the transaction with TransactionID 102 to 165. 
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165
transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [112]:
# ● Add a new column 'Discount' by calculating 10% of the 'Amount'.

transactions['Discount'] = transactions['Amount'] * 0.10
transactions

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0

In [113]:
# ● Remove the row with TransactionID 109. 

transactions = transactions.drop(transactions[transactions['TransactionID'] == 109].index)
transactions

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [114]:
# ● Delete the 'Discount' column from the DataFrame.

transactions = transactions.drop(columns=['Discount'])
transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400